name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24'

    - name: Tests
      run: go test -v github.com/iwa/api-FULLCAPS/cmd/api-fullcaps